; simple program to test my lisp interpreter :^)
(let ((name "user"))
  (setf name "world")
  (display "Hello, ")
  (display name)
  (display "!")
  (newline)
  (display "4 + 5 = ")
  (display (+ 4 5))
  (newline))
(display "out")
(newline)
